version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - /mnt/nas/images:/pb/pb_data/storage # Maps the storage folder to your local root
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    # Expose the Nginx HTTP port (80) to the host. Adjust if you prefer a different external port.
    ports:
      - "3000:80"
    volumes:
      # NEW: Map a separate directory on the NAS for Nginx caching
      - /mnt/nas/nginx_cache:/var/cache/nginx/pb_thumbnails
    environment:
      - VITE_POCKETBASE_URL=/
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  pb_data:

networks:
  app-network:
    driver: bridge